### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by Jeff-Ashear** [Echo-2-Project-3/Better-News-App#1]
- [x] 1. Database works (basic)
 - [x] 2. User accounts
   - [x] Login works
   - [x] Stores challenge participation
   - [x] Avatar
 - [x] 3. Challenges in MVP
    - [x] Social/Staying connected
        - [x] Reach out daily to at least one member of a community you want to maintain during stay at home.  One point per post.
    - [x] Optimism challenge 
        - [x] Post at least one positive thing to the feed per day.  One point per post.
- [x] 4. Leaderboards
    - [x] Keep track of user's rank in each challenge in the database.
    - [x] post the ranking to the user's page
    - [x] Show users in top 5 or ten positions
- [x] 5. Reward system
    - [x] Design two or three trophies.
    - [x] deliver the appropriate trophy upon challenge completion

**Comment by justin1732** [comment]
Good job team!
